---
title: "BM2_HW2"
author: "Yangyang Chen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(viridis)
library(modelr)
library(mgcv)
library(latex2exp)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem_1

### (a)
```{r}
# load data
dose=c(0, 1, 2, 3, 4)## x_i
num=c(30, 30, 30, 30, 30) ## m_i
killed=c(2, 8, 15, 23, 27) ## y_i
data=data.frame(dose,num,killed) ## (x_i, m_i, y_i)
```

```{r}
# data preparation
x=data$dose
y=data$killed
m=data$num
resp=cbind(y,m-y)   #### counts of success (death=1), failure (surv=0)
```

```{r}
glm_logit=glm(resp~x, family=binomial(link='logit'))
glm_probit=glm(resp~x, family=binomial(link='probit'))
glm_clog=glm(resp~x, family=binomial(link='cloglog')) # asymmetric

confint.default(glm_logit) [2,2]
confint.default(glm_probit) [2,2]
confint.default(glm_clog)[2,2]
summary(glm_logit)$deviance
summary(glm_probit)$deviance
summary(glm_clog)$deviance

pred_1 = predict(glm_logit, newdata = data.frame(x = 0.01), type = "response")
pred_2 = predict(glm_probit, newdata = data.frame(x = 0.01), type = "response")
pred_3 = predict(glm_clog, newdata = data.frame(x = 0.01), type = "response")

data.frame(
    estimate_of_beta = c(summary(glm_logit)$coeff[2,1], summary(glm_probit)$coeff[2,1],
                         summary(glm_clog)$coeff[2,1]), 
    ci_lower = c(confint.default(glm_logit) [2,1], confint(glm_probit) [2,1],
                 confint.default(glm_clog)[2,1]),
    ci_upper = c(confint.default(glm_logit) [2,2], confint.default(glm_probit) [2,2],
                 confint.default(glm_clog)[2,2]),
    deviance = c(summary(glm_logit)$deviance, summary(glm_probit)$deviance,
                 summary(glm_clog)$deviance), 
    estimated_probability = c(pred_1, pred_2, pred_3))|>
  knitr::kable(digits = 4)
```

### (b)
```{r}
dose=c(0, 1, 2, 3, 4)## x_i
num=c(30, 30, 30, 30, 30) ## m_i
killed=c(2, 8, 15, 23, 27) ## y_i
data=data.frame(dose,num,killed) ## (x_i, m_i, y_i)

# data preparation
x=data$dose
y=data$killed
m=data$num
resp=cbind(y,m-y)   #### counts of success (death=1), failure (surv=0)
glm_logit=glm(resp~x, family=binomial(link='logit')) 
glm_probit=glm(resp~x, family=binomial(link='probit')) 
glm_clog=glm(resp~x, family=binomial(link='cloglog')) # asymmetric 
summary(glm_logit) # Wald test of coefficients 
summary(glm_probit) 
summary(glm_clog) 

beta0=glm_logit$coefficients[1]
beta1=glm_logit$coefficients[2]
betacov=vcov(glm_logit) # inverse fisher information
x0fit=-beta0/beta1
10^x0fit # point estimate of LD50
varx0=betacov[1,1]/(beta1^2)+betacov[2,2]*(beta0^2)/(beta1^4)-2*betacov[1,2]*beta0/(beta1^3)
c(x0fit,sqrt(varx0)) # point est and se
10^(x0fit+c(qnorm(0.05),-qnorm(0.05))*sqrt(varx0)) # 90% CI for LD50
```

